In [1]:
import numpy as np

In [4]:
data  = np.random.randn(5,6)

In [6]:
data

array([[-0.40170442, -2.09651023,  0.17936822,  0.09477015, -0.14118068,
         0.4891378 ],
       [ 0.26277083,  0.07843127,  0.75722355, -0.98893235,  0.26578375,
         0.71156282],
       [ 1.5052628 , -1.68190781, -0.25377229,  0.77344318, -0.41420951,
         0.90727025],
       [-0.05329999, -0.27240695,  0.78130084, -0.29209146,  1.07729135,
        -0.58881409],
       [ 1.76215119,  0.48843122,  0.26964638, -0.08428399,  0.7818104 ,
        -0.60617106]])

In [7]:
data*10

array([[ -4.01704419, -20.96510227,   1.79368218,   0.94770147,
         -1.41180678,   4.89137801],
       [  2.62770827,   0.78431271,   7.57223555,  -9.88932346,
          2.65783745,   7.11562819],
       [ 15.05262801, -16.81907813,  -2.53772288,   7.73443184,
         -4.1420951 ,   9.0727025 ],
       [ -0.5329999 ,  -2.72406953,   7.81300842,  -2.92091464,
         10.77291346,  -5.88814088],
       [ 17.62151189,   4.88431216,   2.69646383,  -0.84283993,
          7.81810404,  -6.06171056]])

In [8]:
data+data

array([[-0.80340884, -4.19302045,  0.35873644,  0.18954029, -0.28236136,
         0.9782756 ],
       [ 0.52554165,  0.15686254,  1.51444711, -1.97786469,  0.53156749,
         1.42312564],
       [ 3.0105256 , -3.36381563, -0.50754458,  1.54688637, -0.82841902,
         1.8145405 ],
       [-0.10659998, -0.54481391,  1.56260168, -0.58418293,  2.15458269,
        -1.17762818],
       [ 3.52430238,  0.97686243,  0.53929277, -0.16856799,  1.56362081,
        -1.21234211]])

In [9]:
data.shape

(5, 6)

In [10]:
data.dtype

dtype('float64')

In [11]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 4)

In [16]:
np.zeros((5,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.empty((2,5,6))

array([[[1.25879883e-311, 1.25874707e-311, 6.32300944e+233,
         4.44387685e+252, 3.74168656e+233, 6.45757137e+270],
        [8.48585409e-096, 1.96082954e+243, 5.31435408e-119,
         1.04990427e-153, 1.15297376e-259, 8.94213159e+130],
        [8.36280712e+165, 5.69559448e-119, 6.01347002e-154,
         1.04990528e-153, 4.36377119e+169, 2.00007434e+174],
        [2.88987565e+204, 6.19588734e+223, 3.99166068e+252,
         5.15194298e-308, 1.25878164e-311, 1.25876413e-311],
        [1.63857376e+248, 4.78179676e+180, 1.17567372e+214,
         7.04134365e-009, 1.17234088e+214, 5.38227080e+228]],

       [[1.41475216e+195, 7.79162003e+140, 6.07849924e+247,
         9.48287275e-076, 6.99418523e-009, 4.72163065e+257],
        [3.74857394e+233, 1.05894667e-153, 2.02646854e+267,
         7.27432674e+199, 6.07883627e+247, 8.44306401e-053],
        [5.60235865e-067, 8.98108651e-120, 4.83245960e+276,
         5.14659111e-308, 1.25880017e-311, 1.25874718e-311],
        [6.09941574e-154, 5.15

In [18]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])